#!/bin/sh -e

# This script will run the first time the system boots. Even
# though we've told it to run after networking is enabled,
# I've observed inconsistent behavior if we start hitting the
# net immediately.
#
# Introducing a brief sleep makes things work right all the
# time.

# Remove our firstboot service so that it won't run again
update-rc.d firstboot remove

echo "Installing AllStar Asterisk, Please wait"

sleep 30

###############
# start of script

# DL x86 script
cd /srv
wget https://github.com/N4IRS/AllStar/raw/master/x86.tar

# untar x86 script
tar xvf x86.tar

# run x86_allstar_install
# need to tweak this for required libs and build tools are not run
x86_allstar_asterisk_install.sh

# end of script
################

# Reboot into the system
echo "AllStar Asterisk install Complete, rebooting"

sleep 5

/sbin/reboot

