#!/bin/sh

# grab our firstboot script and put in in /usr/local/bin
wget https://github.com/N4IRS/AllStar/raw/master/firstboot -O /usr/local/bin/firstboot
wget https://github.com/N4IRS/AllStar/raw/master/patches/patch-firstboot-rc.local -O /tmp/patch-firstboot-rc.local

chmod +x /usr/local/bin/firstboot

# modify rc.local to run firstboot
cd /etc
patch </tmp/patch-firstboot-rc.local

echo "finished post install"

